"""
Django settings for traveling project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w0jpt$a7g*@3fvv^_9wls#+gi5ur^rlcqmyt6$b_s)_&z%db=a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

CSRF_TRUSTED_ORIGINS = [
    "https://api.cheaptickethub.com",
    "https://www.api.cheaptickethub.com",
]
ALLOWED_HOSTS = ['*',"api.cheaptickethub.com", "www.api.cheaptickethub.com"]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'accounts',
    'drf_spectacular',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'traveling.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'traveling.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Traveling API',
    'DESCRIPTION': 'API for Traveling Application with OTP and Auth',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

CORS_ALLOW_ALL_ORIGINS = True


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apparatusasmail@gmail.com'
EMAIL_HOST_PASSWORD = 'pmmf fbvk kypp flqg'
DEFAULT_FROM_EMAIL = 'support@cheaptickethub.com'



GLOBAL_AUTH_REQUIRED = True





#unfold admin panel
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

def dashboard_callback(request, context):
    context.update({
        "subtitle": "Overview",
        "description": "Welcome to CheapTicket Portal. Here is your daily activity overview.",
        "custom_style": True,
        "kpi": [
            {
                "title": "Arrivals",
                "icon": "flight_land",
                "metric": "54",
                "footer": "This week",
                "chart": [10, 20, 15, 30, 20, 54],
            },
            {
                "title": "Departures",
                "icon": "flight_takeoff",
                "metric": "12",
                "footer": "This week",
                "chart": [5, 5, 10, 8, 12, 12],
            },
            {
                "title": "Total Bookings",
                "icon": "airplane_ticket",
                "metric": "1,245",
                "footer": "+12% Growth",
            },
            {
                "title": "Multi-City Flights",
                "icon": "vibration",
                "metric": "18",
                "footer": "This month",
            },

        ],
    })
    return context

UNFOLD = {
    "SITE_TITLE": "CheapTicket Admin",
    "SITE_HEADER": "CheapTicket Portal",
    "SITE_URL": "/",
    "DASHBOARD_CALLBACK": "traveling.settings.dashboard_callback",
    "SHOW_HISTORY": True,  # Enable Recent actions widget
    "STYLES": [
        lambda request: "https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap",
        lambda request: "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0",
        lambda request: """
            <style>
                :root {
                    --font-family-sans: 'Outfit', sans-serif;
                }
                body {
                    font-family: var(--font-family-sans);
                    font-size: 16px;
                }
                
                /* Sidebar tweaks */
                .sidebar-nav-link {
                    font-size: 0.95rem;
                    font-weight: 500;
                }

                /* Table tweaks for professional look */
                #result_list th {
                    font-weight: 700;
                    text-transform: uppercase;
                    letter-spacing: 0.05em;
                    font-size: 0.85rem;
                }
                #result_list td {
                    padding-top: 1rem;
                    padding-bottom: 1rem;
                    font-size: 0.95rem;
                }
                
                /* Dashboard cards */
                .dashboard-card {
                    box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1);
                    border-radius: 0.75rem;
                }

                /* Icons for Model List in Dashboard/App Index */
                /* Target the anchor links in the model list rows */
                .model-flight a::before, a[href*="/accounts/flight/"]::before { content: "\\e539"; }
                .model-multicityflight a::before, a[href*="/accounts/multicityflight/"]::before { content: "\\e539"; }
                .model-hotel a::before, a[href*="/accounts/hotel/"]::before { content: "\\e53a"; }

                .model-cruise a::before, a[href*="/accounts/cruise/"]::before { content: "\\e532"; }
                .model-rentalcar a::before, a[href*="/accounts/rentalcar/"]::before { content: "\\e531"; }
                .model-holidaypackage a::before, a[href*="/accounts/holidaypackage/"]::before { content: "\\eb3e"; }
                .model-customer a::before, a[href*="/accounts/customer/"]::before { content: "\\e87c"; }
                .model-authuser a::before, a[href*="/auth/authuser/"]::before { content: "\\e7fb"; }
                
                /* Common icon style */
                a[href*="/accounts/"]::before {
                    font-family: 'Material Symbols Outlined';
                    font-weight: normal;
                    font-style: normal;
                    font-size: 20px;
                    line-height: 1;
                    letter-spacing: normal;
                    text-transform: none;
                    display: inline-block;
                    white-space: nowrap;
                    word-wrap: normal;
                    direction: ltr;
                    margin-right: 10px;
                    vertical-align: middle;
                    color: #d97706; /* Amber-600 */
                }

                /* Row Hover Effect to remove dullness */
                 tr.model-row:hover, .results tr:hover {
                    background-color: #fef3c7 !important; /* Amber-100 */
                    transition: background-color 0.2s;
                }
                /* Fix for Theme Toggle / User Menu Dropdown Width */
                div[role="menu"], .group:hover .group-hover\:block {
                    min-width: 16rem !important;
                    width: auto !important;
                }
                div[role="menu"] a, div[role="menu"] button {
                    white-space: nowrap;
                    padding-right: 1.5rem;
                }
            </style>
        """,
    ],
    "SCRIPTS": [
        lambda request: """
            <script>
                (function() {
                    // Function to add Save button to date picker
                    function addSaveButton(calendar) {
                        if (!calendar || calendar.querySelector('.datepicker-save-btn')) {
                            return; // Already has save button or invalid calendar
                        }
                        
                        // Find or create footer
                        let footer = calendar.querySelector('.flatpickr-footer, .flatpickr-buttons');
                        if (!footer) {
                            // Look for any container with buttons
                            const cancelBtn = calendar.querySelector('button');
                            if (cancelBtn && cancelBtn.textContent.toLowerCase().includes('cancel')) {
                                footer = cancelBtn.parentElement;
                            }
                        }
                        
                        if (!footer) {
                            // Create new footer
                            footer = document.createElement('div');
                            footer.className = 'flatpickr-footer';
                            footer.style.cssText = 'display: flex; gap: 8px; padding: 12px; border-top: 1px solid #e5e7eb;';
                            calendar.appendChild(footer);
                        }
                        
                        // Create Save button
                        const saveBtn = document.createElement('button');
                        saveBtn.textContent = 'Save';
                        saveBtn.className = 'datepicker-save-btn';
                        saveBtn.type = 'button';
                        saveBtn.style.cssText = `
                            background-color: #d97706;
                            color: white;
                            border: none;
                            padding: 8px 16px;
                            border-radius: 6px;
                            font-weight: 500;
                            cursor: pointer;
                            transition: background-color 0.2s;
                        `;
                        
                        // Hover effects
                        saveBtn.addEventListener('mouseenter', () => {
                            saveBtn.style.backgroundColor = '#b45309';
                        });
                        saveBtn.addEventListener('mouseleave', () => {
                            saveBtn.style.backgroundColor = '#d97706';
                        });
                        
                        // Save functionality
                        saveBtn.addEventListener('click', () => {
                            // Get the flatpickr instance
                            const fpInstance = calendar._flatpickr;
                            if (fpInstance) {
                                fpInstance.close();
                            } else {
                                // Fallback: hide calendar
                                calendar.style.display = 'none';
                                if (calendar.classList.contains('open')) {
                                    calendar.classList.remove('open');
                                }
                            }
                        });
                        
                        // Add Save button before Cancel
                        const cancelBtn = footer.querySelector('button');
                        if (cancelBtn) {
                            footer.insertBefore(saveBtn, cancelBtn);
                        } else {
                            footer.appendChild(saveBtn);
                        }
                    }
                    
                    // Password toggle logic
                    function setupPasswordToggle() {
                        // Ensure font is loaded
                        if (!document.getElementById('material-symbols-font')) {
                            const fontLink = document.createElement('link');
                            fontLink.id = 'material-symbols-font';
                            fontLink.rel = 'stylesheet';
                            fontLink.href = 'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0';
                            document.head.appendChild(fontLink);
                        }

                        const passwordInputs = document.querySelectorAll('input[type="password"]');
                        passwordInputs.forEach(passwordInput => {
                            if (passwordInput.dataset.toggleSetup === 'true') return;

                            // Create toggle button
                            const toggleBtn = document.createElement('span');
                            toggleBtn.className = 'material-symbols-outlined password-toggle-icon';
                            toggleBtn.textContent = 'visibility';
                            toggleBtn.setAttribute('style', `
                                position: absolute !important;
                                right: 12px !important;
                                top: 50% !important;
                                transform: translateY(-50%) !important;
                                cursor: pointer !important;
                                color: #d97706 !important; /* Amber-600 to match theme */
                                user-select: none !important;
                                z-index: 100 !important;
                                font-size: 22px !important;
                                display: flex !important;
                                align-items: center !important;
                                justify-content: center !important;
                                height: 100% !important;
                            `);

                            // Django Unfold structure fix
                            const parent = passwordInput.parentElement;
                            if (parent) {
                                parent.style.position = 'relative';
                                parent.appendChild(toggleBtn);
                                
                                // Ensure input doesn't hide behind icon
                                passwordInput.style.paddingRight = '45px';
                                
                                toggleBtn.onclick = function(e) {
                                    e.preventDefault();
                                    e.stopPropagation();
                                    if (passwordInput.type === 'password') {
                                        passwordInput.type = 'text';
                                        toggleBtn.textContent = 'visibility_off';
                                    } else {
                                        passwordInput.type = 'password';
                                        toggleBtn.textContent = 'visibility';
                                    }
                                };
                                
                                passwordInput.dataset.toggleSetup = 'true';
                            }
                        });
                    }


                    // Check for existing elements on load
                    document.addEventListener('DOMContentLoaded', () => {
                        // For calendars
                        setTimeout(() => {
                            const existingCalendars = document.querySelectorAll('.flatpickr-calendar');
                            existingCalendars.forEach(cal => addSaveButton(cal));
                        }, 500);

                        // For password toggle
                        setupPasswordToggle();
                        setTimeout(setupPasswordToggle, 500);
                    });

                    // Also watch for mutations
                    const appObserver = new MutationObserver((mutations) => {
                        mutations.forEach((mutation) => {
                            mutation.addedNodes.forEach((node) => {
                                if (node.nodeType === 1) {
                                    // Check for calendars
                                    if (node.classList && node.classList.contains('flatpickr-calendar')) {
                                        setTimeout(() => addSaveButton(node), 100);
                                    }
                                    const calendars = node.querySelectorAll && node.querySelectorAll('.flatpickr-calendar');
                                    if (calendars && calendars.length > 0) {
                                        calendars.forEach(cal => {
                                            setTimeout(() => addSaveButton(cal), 100);
                                        });
                                    }
                                }
                            });
                        });
                        setupPasswordToggle();
                    });
                    appObserver.observe(document.body, { childList: true, subtree: true });

                })();
            </script>


        """,
    ],
    "COLORS": {
        "primary": {
            "50": "255 251 235",
            "100": "254 243 199",
            "200": "253 230 138",
            "300": "252 211 77",
            "400": "251 191 36",
            "500": "245 158 11",
            "600": "217 119 6",
            "700": "180 83 9",
            "800": "146 64 14",
            "900": "120 53 15",
            "950": "69 26 3",
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇬🇧",
                "fr": "🇫🇷",
                "nl": "🇧🇪",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Main"),
                "separator": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("User Management"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_authuser_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                    {
                        "title": _("Customers"),
                        "icon": "face",
                        "link": reverse_lazy("admin:accounts_customer_changelist"),
                    },
                ],
            },
            {
                "title": _("Bookings"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Flights"),
                        "icon": "flight",
                        "link": reverse_lazy("admin:accounts_flight_changelist"),
                    },
                    {
                        "title": _("Multi-City Flights"),
                        "icon": "flight_takeoff",
                        "link": reverse_lazy("admin:accounts_multicityflight_changelist"),
                    },

                    {
                        "title": _("Hotels"),
                        "icon": "hotel",
                        "link": reverse_lazy("admin:accounts_hotel_changelist"),
                    },
                    {
                        "title": _("Cruises"),
                        "icon": "directions_boat",
                        "link": reverse_lazy("admin:accounts_cruise_changelist"),
                    },
                    {
                        "title": _("Rental Cars"),
                        "icon": "directions_car",
                        "link": reverse_lazy("admin:accounts_rentalcar_changelist"),
                    },
                    {
                        "title": _("Holiday Packages"),
                        "icon": "beach_access",
                        "link": reverse_lazy("admin:accounts_holidaypackage_changelist"),
                    },
                ],
            },
        ],
    },
}
