# Generated by Django 6.0.1 on 2026-01-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='date_range',
        ),
        migrations.AddField(
            model_name='hotel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
