# Generated by Django 6.0.1 on 2026-01-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_hotel_date_range_hotel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
