# Generated by Django 6.0.1 on 2026-01-30 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hotel_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='customer_name',
        ),
    ]
