# Generated by Django 6.0.1 on 2026-01-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rentalcar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='date',
            new_name='departure_date',
        ),
        migrations.AddField(
            model_name='flight',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
