# Generated by Django 6.0.1 on 2026-01-30 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_date_flight_departure_date_flight_return_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_location', models.CharField(max_length=255)),
                ('from_location', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holiday_packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
