# Generated by Django 6.0.1 on 2026-01-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_name_user_address_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='adults',
            new_name='passengers',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='children',
        ),
    ]
