# Generated by Django 6.0.1 on 2026-01-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_adults_flight_passengers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='passengers',
        ),
        migrations.AddField(
            model_name='flight',
            name='adults',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='adults',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='adults',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rentalcar',
            name='adults',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rentalcar',
            name='children',
            field=models.IntegerField(default=0),
        ),
    ]
