# Generated by Django 6.0.1 on 2026-01-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_flight_passengers_flight_adults_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaypackage',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='holidaypackage',
            name='children',
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='passengers',
            field=models.IntegerField(default=1),
        ),
    ]
