# Generated by Django 6.0.1 on 2026-01-30 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_holidaypackage_adults_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_location', models.CharField(max_length=255)),
                ('from_location', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('cabins', models.IntegerField()),
                ('adults', models.IntegerField(default=0)),
                ('children', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cruises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
