# Generated by Django 6.0.1 on 2026-01-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_cruise'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='coupon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='coupon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='coupon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='coupon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='coupon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
