# Generated by Django 6.0.1 on 2026-01-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_cruise_coupon_flight_coupon_holidaypackage_coupon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalcar',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='rentalcar',
            name='children',
        ),
        migrations.AlterField(
            model_name='cruise',
            name='coupon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='coupon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='coupon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='coupon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rentalcar',
            name='coupon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
