# Generated by Django 6.0.1 on 2026-01-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_rentalcar_adults_remove_rentalcar_children_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaypackage',
            name='passengers',
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='adults',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='children',
            field=models.IntegerField(default=0),
        ),
    ]
