# Generated by Django 6.0.1 on 2026-01-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_holidaypackage_passengers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='date',
            new_name='checkin_date',
        ),
        migrations.AddField(
            model_name='hotel',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='cabins',
            field=models.CharField(max_length=255),
        ),
    ]
