# Generated by Django 4.2.1 on 2026-02-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_otplog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
